### ISSUE TITLE
Restore failed 

### ISSUE THREAD

**Issue by michaelmcguinness** [lekoder/consul-to-json#3]
I've been using this utility successfully but recently the restore failed. The difference from before was that the JSON file was relatively large compared to before (30Mb) and heavily populated with Hashicorp Vault entries which consisted of non-printable characters. 

`$ consul-to-json restore consul_backup_1610031200.json`
`Maximum call stack size exceeded`

I recovered this by manually removing the Vault entries which at this point I was not yet using.

**Comment by lekoder** [comment]
Thanks for the report @michaelmcguinness. It's most likely caused by underlying `consul-kv-object` lib, I'm going to try to replicate and fix it there.

**Comment by lekoder** [comment]
Using `consul-kv-object` 1.0.1 or later should fix this issue, tested for up to 1e5 keys. If more keys in backup/restore are desired, `consul-to-json` should be redesigned.

**Comment by lekoder** [comment]
@michaelmcguinness Just published `consul-to-json` `v0.2.3` which should not be affected by this bug - as long as your JSON fits in memory.
